---
- name: Using network filter
  hosts: localhost
  vars:
    my_list:
      - 10.0.0.1/24
      - 192.168.1.2/24
      - 8.8.4.2
      - 1.1.1.1
      - redhat.com
      - lwsus.com
  tasks:
  - name: Gather the network information
    ansible.builtin.setup:
      gather_subset: 
      - '!all'
      - network
    register: network_facts

  - name: Print the network_facts
    ansible.builtin.debug:
      var: network_facts
