---
- name: Working with filters
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Create user 
    ansible.builtin.user:
      name: "{{ myname | default('lenovo') }}"
      state: present
    delegate_to: servera.lab.example.com
...
