---
- name: add block of text to the test file 
  hosts: webservers
  tasks:
  - name: file creation
    ansible.builtin.file:
      path: /tmp/test
      state: touch

  - name: Add a block of text to an existing file
    ansible.builtin.blockinfile:
      path: /tmp/test
      block: |
        After the RH294 Training
        You can go with the Advance Module of Ansible Automation (DO374)
      state: present
...
