---
- name: Using the boolean to decide the action
  hosts: all
  vars:
    my_task: true
  tasks:
  - name: Install the required package
    ansible.builtin.dnf:
      name: vsftpd
      state: latest
    when: my_task
...
