---
- name: Using copy module 
  hosts: webservers
  tasks:
  - name: Copy a file to the managed host and set the attributes 
    ansible.builtin.copy:
      src: file.txt
      dest: /tmp/test123
      owner: devops
      group: devops
      mode: u+rw,g-wx,o-rwx
      setype: samba_share_t
...
