---
- name: Understanding handlers
  hosts: all
  become: true
  tasks:
  - name: Print the custom message
    ansible.builtin.debug:
      msg: "Showing handlers demo"

  - name: Install package
    ansible.builtin.yum: 
      name: httpd 
      state: latest
    notify: restart apache

  handlers:
  - name: restart apache
    ansible.builtin.service: 
      name: httpd 
      state: restarted 
      enabled: true
...

