---
- name: Install the package based on condition
  hosts: dev
  become: true
  tasks:
  - name: Install the package
    ansible.builtin.dnf: 
      name: httpd
      state: latest
    when: ansible_facts['memfree_mb'] > 500
...
