---
- name: Add sample text to the file 
  hosts: webservers
  tasks:
  - name: Add a single line of text to the file
    ansible.builtin.lineinfile:
      path: /tmp/test123
      line: Welcome to Red Hat Training
      state: present
...
