---
- name: Register variables example
  hosts: all
  gather_facts: false
  tasks:
  - name: Looping Test
    ansible.builtin.shell: "echo This is my item: {{ item }}"
    loop:
    - one
    - two
    register: echo_results

  - name: Display the results
    ansible.builtin.debug:
      var: echo_results
...
