---
- name: Package facts demo
  hosts: webservers
  become: true
  gather_facts: true
  tasks:
  - name: Ensure package facts are gathered
    ansible.builtin.package_facts:

  - name: Display the package afcts
    ansible.builtin.debug:
      var: ansible_facts['packages']
...
