download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/gmarcy-ansible-1.0.0.tar.gz
format_version: 1.0.0
name: ansible
namespace: gmarcy
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/gmarcy/ansible/versions/1.0.0/
