---
- name: Using tags
  hosts: web_servers
  become: true
  tasks:
  - name: Remove the tree package
    ansible.builtin.dnf:
      name: tree
      state: absent
    tags:
    - remove
  - name: Update the package
    ansible.builtin.dnf:
      name: tree
      state: latest
    tags:
    - update
...
