---
- name: Using simple loop
  hosts: all
  become: true
  tasks:
  - name: Service update
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    loop:
    - crond
    - atd
...
